# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 18:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160323_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contactInfo',
            field=models.CharField(max_length=255, verbose_name='Contact Information'),
        ),
    ]
