# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 18:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160707_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventDate',
        ),
        migrations.AddField(
            model_name='event',
            name='beneficiaries',
            field=models.CharField(default=datetime.datetime(2016, 7, 7, 18, 55, 38, 631881, tzinfo=utc), max_length=255, verbose_name='Number of beneficiaries'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='eventCoverage',
            field=models.TextField(blank=True, verbose_name='Event Geographical Objectives'),
        ),
        migrations.AddField(
            model_name='event',
            name='eventDateEnd',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 7, 18, 55, 49, 775803, tzinfo=utc), verbose_name='Event End Date and Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='eventDateStart',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 7, 18, 56, 8, 563414, tzinfo=utc), verbose_name='Event Start Date and Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='otherInformation',
            field=models.TextField(blank=True, verbose_name='Other Information (private)'),
        ),
        migrations.AddField(
            model_name='event',
            name='report',
            field=models.TextField(blank=True, verbose_name='Report (private)'),
        ),
    ]
