# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160707_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='additionalDocument',
            field=models.FileField(blank=True, null=True, upload_to='events', verbose_name='Additional Document'),
        ),
        migrations.AlterField(
            model_name='event',
            name='mainDocument',
            field=models.FileField(blank=True, null=True, upload_to='events', verbose_name='Main Document'),
        ),
    ]
