# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160707_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='communication',
            field=models.TextField(blank=True, null=True, verbose_name='Communication text'),
        ),
    ]
