# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-09 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160707_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='indexText',
            field=models.TextField(blank=True, verbose_name='Parsed text for indexing'),
        ),
        migrations.AddField(
            model_name='event',
            name='indexText',
            field=models.TextField(blank=True, verbose_name='Parsed text for indexing'),
        ),
        migrations.AddField(
            model_name='resource',
            name='indexText',
            field=models.TextField(blank=True, verbose_name='Parsed text for indexing'),
        ),
    ]
