# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-10 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160709_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('type', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('searchTs', models.DateTimeField(auto_now_add=True, verbose_name='Search timestamp')),
                ('total', models.IntegerField(verbose_name='Search query')),
                ('query', models.CharField(max_length=512, verbose_name='Search query')),
            ],
        ),
    ]
