# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-10 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_search_searchlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchlog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
